.. keystone documentation master file, created by
   sphinx-quickstart on Mon May 23 07:54:13 2016.
   You can adapt this file completely to your liking, but it should at least
   contain the root `toctree` directive.

Welcome to keystone's documentation!
====================================

Contents:

.. toctree::
   :maxdepth: 2

   v3/authenticate-v3.inc
   v3/credentials
   v3/domains
   v3/domains-config-v3
   v3/groups
   v3/identity_v3_OS-OAUTH1
   v3/policies
   v3/projects
   v3/regions-v3
   v3/roles
   v3/service-catalog
   v3/users


Indices and tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`

