#!/usr/bin/env bash

set -ex

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y \
  python3-venv
python3 -m venv $HOME/.local/tools
source $HOME/.local/tools/bin/activate
pip install -U \
  pip \
  bindep \
  tox

cd source
apt-get install -y \
  $(bindep -b test)
git config --global --add safe.directory /source

export UPPER_CONSTRAINTS_FILE=https://raw.githubusercontent.com/sapcc/requirements/stable/2025.1-m3/upper-constraints.txt
export \
  KEYSTONE_IDENTITY_BACKEND=ldap \
  KEYSTONE_CLEAR_LDAP=yes \
  ENABLE_LDAP_LIVE_TEST=true
tox -e py312 \
  --skip-missing-interpreters=false
