# variables in header
x-openstack-request-id:
  description: |
    A unique request ID that provides tracking for
    the request. Provider must configure middleware to return a
    request ID header in a response.
  in: header
  required: false
  type: string

# variables in path

# variables in query

# variables in body
access:
  description: |
    An ``access`` object.
  in: body
  required: true
  type: object
alias:
  description: |
    The alias for the extension. For example,
    "FOXNSOX", "os- availability-zone", "os-extended-quotas", "os-
    share-unmanage" or "os-used-limits."
  in: body
  required: true
  type: string
api_ext_description:
  description: |
    The extension description.
  in: body
  required: true
  type: string
api_ext_name:
  description: |
    The name of the extension. For example, "Fox In
    Socks."
  in: body
  required: true
  type: string
enabled:
  description: |
    Indicates whether the tenant is enabled or
    disabled.
  in: body
  required: true
  type: boolean
endpoints:
  description: |
    One or more ``endpoints`` objects. Each object
    shows the ``adminURL``, ``region``, ``internalURL``, ``id``, and
    ``publicURL`` for the endpoint.
  in: body
  required: true
  type: array
endpoints_links:
  description: |
    Links for the endpoint.
  in: body
  required: true
  type: array
expires:
  description: |
    The date and time when the token expires.

    The date and time stamp format is `ISO 8601
    <https://en.wikipedia.org/wiki/ISO_8601>`_:

    ::

       CCYY-MM-DDThh:mm:ss.sssZ

    For example, ``2015-08-27T09:49:58.000000Z``.

    A ``null`` value indicates that the token never expires.
  in: body
  required: true
  type: string
id:
  description: |
    The token ID. This field is required in the
    ``token`` object.
  in: body
  required: false
  type: string
impersonation:
  description: |
    The impersonation flag.
  in: body
  required: false
  type: boolean
issued_at:
  description: |
    The date and time when the token was issued.

    The date and time stamp format is `ISO 8601
    <https://en.wikipedia.org/wiki/ISO_8601>`_:

    ::

       CCYY-MM-DDThh:mm:ss.sssZ

    For example, ``2015-08-27T09:49:58.000000Z``.
  in: body
  required: true
  type: string
metadata:
  description: |
    A ``metadata`` object.
  in: body
  required: true
  type: object
name:
  description: |
    Endpoint name.
  in: body
  required: true
  type: string
password:
  description: |
    The password of the user. Required if you include
    the ``passwordCredentials`` object. Otherwise, you must provide a
    token.
  in: body
  required: false
  type: string
passwordCredentials:
  description: |
    A ``passwordCredentials`` object. To
    authenticate, you must provide either a user ID and password or a
    token.
  in: body
  required: false
  type: string
serviceCatalog:
  description: |
    List of ``serviceCatalog`` objects.
  in: body
  required: true
  type: array
signed:
  description: |
    List of expired PKI tokens, signed by associated
    cryptographic message syntax (CMS).
  in: body
  required: true
  type: string
tenant:
  description: |
    A ``tenant`` object.
  in: body
  required: true
  type: object
tenant_description:
  description: |
    Description about the tenant.
  in: body
  required: true
  type: string
tenantId:
  description: |
    The tenant ID. Both the ``tenantId`` and
    ``tenantName`` attributes are optional and mutually exclusive. If
    you specify both attributes, the server returns the ``Bad Request
    (400)`` response code.
  in: body
  required: false
  type: string
tenantId_response:
  description: |
    The tenant ID.
  in: body
  required: true
  type: string
tenantName:
  description: |
    The tenant name. Both the ``tenantId`` and
    ``tenantName`` attributes are optional and mutually exclusive. If
    you specify both attributes, the server returns the ``Bad Request
    (400)`` response code.
  in: body
  required: false
  type: string
tenantName_response:
  description: |
    The tenant name.
  in: body
  required: true
  type: string
tenants:
  description: |
    One or more tenant Objects.
  in: body
  required: true
  type: array
tenants_links:
  description: |
    Links of the tenants.
  in: body
  required: true
  type: array
token:
  description: |
    A ``token`` object. Required if you do not
    provide a password credential.
  in: body
  required: false
  type: object
trust:
  description: |
    A ``trust`` object.
  in: body
  required: false
  type: object
trustee_user_id:
  description: |
    The trustee user ID.
  in: body
  required: false
  type: string
trustor_user_id:
  description: |
    The trustor user ID.
  in: body
  required: false
  type: string
type:
  description: |
    Endpoint type.
  in: body
  required: true
  type: string
updated:
  description: |
    The date and time stamp when the extension was
    last updated.
  in: body
  required: true
  type: string
user:
  description: |
    A ``user`` object, which shows the ``username``,
    ``roles_links``, ``id``, ``roles``, and ``name``.
  in: body
  required: true
  type: object
username:
  description: |
    The user name. Required if you include the
    ``passwordCredentials`` object. Otherwise, you must provide a
    token.
  in: body
  required: false
  type: string

