ALTER TABLE users ALTER COLUMN enabled DROP DEFAULT;
ALTER TABLE users ALTER COLUMN enabled TYPE integer USING CASE enabled WHEN true THEN 1 ELSE 0 END;

ALTER TABLE tenants ALTER COLUMN enabled DROP DEFAULT;
ALTER TABLE tenants ALTER COLUMN enabled TYPE integer USING CASE enabled WHEN true THEN 1 ELSE 0 END;
