# variables in header
Location:
  format: uri
  in: header
  required: false
  type: string

# variables in path
credential_type:
  description: |
    The credential type.
  in: path
  required: true
  type: string
role_id_path:
  description: |
    The role ID.
  in: path
  required: true
  type: string
role_name_path:
  description: |
    The role name.
  in: path
  required: true
  type: string
service_id_path:
  description: |
    The service ID.
  in: path
  required: true
  type: string
service_name_path:
  description: |
    The service name.
  in: path
  required: true
  type: string
tenant_id_path:
  description: |
    The tenant ID.
  in: path
  required: true
  type: string
user_id_path:
  description: |
    The user ID.
  in: path
  required: true
  type: string

# variables in query

# variables in body
role_description:
  description: |
    The role description.
  in: body
  required: true
  type: string
role_id:
  description: |
    The role ID.
  in: body
  required: true
  type: integer
role_links:
  description: |
    Role links.
  in: body
  required: true
  type: object
role_name:
  description: |
    The role name.
  in: body
  required: true
  type: string
roles:
  description: |
    A ``roles`` object.
  in: body
  required: true
  type: string
service_description:
  description: |
    Description about the service.
  in: body
  required: true
  type: string
service_id:
  description: |
    The ID of the service.
  in: body
  required: true
  type: string
service_name:
  description: |
    The service name.
  in: body
  required: true
  type: string
service_type:
  description: |
    The type of the service.
  in: body
  required: true
  type: string
tenant:
  description: |
    The tenant object.
  in: body
  required: true
  type: object
tenant_description:
  description: |
    Description about the tenant.
  in: body
  required: true
  type: string
tenant_enabled:
  description: |
    Indicates whether the tenant is enabled or
    disabled. Default is ``true``.
  in: body
  required: true
  type: boolean
tenant_id_request:
  description: |
    The tenant ID.
  in: body
  required: true
  type: string
tenant_id_response:
  description: |
    The tenant ID.
  in: body
  required: true
  type: string
tenant_name:
  description: |
    The tenant name.
  in: body
  required: true
  type: string
user:
  description: |
    The ``user`` object.
  in: body
  required: true
  type: string
user_email:
  description: |
    The user email.
  in: body
  required: true
  type: string
user_enabled:
  description: |
    Indicates whether the user should be enabled (``true``)
    or disabled(``false``).
  in: body
  required: true
  type: boolean
user_id_response:
  description: |
    The user ID.
  in: body
  required: true
  type: string
user_links:
  description: |
    The links of ``users`` object.
  in: body
  required: true
  type: array
user_name:
  description: |
    The user in-real-life name.
  in: body
  required: true
  type: string
user_new_password:
  description: |
    User's new password
  in: body
  required: true
  type: string
user_original_password:
  description: |
    User's old password
  in: body
  required: true
  type: string
users:
  description: |
    The ``users`` object.
  in: body
  required: true
  type: array
