# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  workflow_dispatch:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Run test
      run: |
        python3 -c "print('all tests have passed')"

    - uses: mshick/add-pr-comment@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        message: |
          Mapping summary for "My Cool Snapshot!" (compared with "Version 1.0.3" at 2021-09-02 13:54:56 GMT): 
          * 1 endpoint added
          * 1 endpoint removed
          * 8 endpoints changed

          You can view the full summary using this link: https://demo.seekret.com/default/changes?revisionLeft=%22f18d4140-dd31-4e94-93c6-73ad1f060a72%22&revisionRight=%22e0bad10f-a01a-4765-86e2-2723baeaef76%22
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
        allow-repeats: false # This is the default
